export const districts = {
  "01": "Raffles Place",
  "02": "Raffles Place",
  "03": "Raffles Place",
  "04": "Raffles Place",
  "05": "Raffles Place",
  "06": "Raffles Place",
  "07": "Tanjong Pagar",
  "08": "Tanjong Pagar",
  "09": "Telok Blangah",
  10: "Telok Blangah",
  11: "Pasir Panjang",
  12: "Pasir Panjang",
  13: "Pasir Panjang",
  14: "Queenstown",
  15: "Queenstown",
  16: "Queenstown",
  17: "Beach Road",
  18: "Golden Mile",
  19: "Golden Mile",
  20: "Little India",
  21: "Little India",
  22: "Orchard Road",
  23: "Orchard Road",
  24: "Bukit Timah",
  25: "Bukit Timah",
  26: "Bukit Timah",
  27: "Bukit Timah",
  28: "Novena",
  29: "Novena",
  30: "Novena",
  31: "Toa Payoh",
  32: "Toa Payoh",
  33: "Toa Payoh",
  34: "Macpherson",
  35: "Macpherson",
  36: "Macpherson",
  37: "Macpherson",
  38: "Geylang",
  39: "Geylang",
  40: "Geylang",
  41: "Geylang",
  42: "Katong",
  43: "Katong",
  44: "Katong",
  45: "Katong",
  46: "Bedok",
  47: "Bedok",
  48: "Bedok",
  49: "Changi",
  50: "Changi",
  81: "Changi",
  51: "Tampines",
  52: "Tampines",
  53: "Punggol",
  54: "Punggol",
  55: "Punggol",
  82: "Punggol",
  56: "Bishan",
  57: "Bishan",
  58: "Upper Bukit Timah",
  59: "Upper Bukit Timah",
  60: "Jurong",
  61: "Jurong",
  62: "Jurong",
  63: "Jurong",
  64: "Jurong",
  65: "Choa Chu Kang",
  66: "Choa Chu Kang",
  67: "Choa Chu Kang",
  68: "Choa Chu Kang",
  69: "Lim Chu Kang",
  70: "Lim Chu Kang",
  71: "Lim Chu Kang",
  72: "Kranji",
  73: "Kranji",
  75: "Yishun",
  76: "Yishun",
  77: "Upper Thomson",
  78: "Upper Thomson",
  79: "Seletar",
  80: "Seletar",
};
